import type { Metadata } from "next";
import "./globals.css";
import "../css/style.css";
import ApolloProviderWrapper from "./ClientProvider"; // Import the Apollo Provider
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body>
        <ApolloProviderWrapper>
        {children}
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
