import type { Metadata } from "next";
import "./globals.css";

import Footer_v1 from "@/compoments/footer/Footer_v1";

import Navbar_v1 from "@/compoments/navbar/Navbar_v1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <Navbar_v1 />
        {children}
        <Footer_v1 />
      </body>
    </html>
  );
}