name: MySQL CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up Prisma and MySQL
        env:
          DATABASE_URL: mysql://testuser:testpassword@127.0.0.1:3306/testdb
        run: |
          npx prisma generate
          npx prisma migrate dev --name init

      - name: Run tests
        env:
          DATABASE_URL: mysql://testuser:testpassword@127.0.0.1:3306/testdb
        run: npm test
