name: MySQL CI

on: [push, pull_request]

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -u root --password=root && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run MySQL Command
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"
